version: '3'

# containers
services:
  api:
    build: .
    container_name: api
    ports:
    # hostlocal:container
      - 3001:3001
    volumes:
      - .:/app
    tty: true # sobe o container, roda os cmd e mantem
    stdin_open: true # permite digitar no terminal
    command: sh
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3386
      MYSQL_USER: root
      DATABASE_PASSWORD: killjoy
      PORT: 3001
    depends_on:
      - database

  database:
    image: mysql:8.0.32
    container_name: database
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: killjoy
